import { OsintAuthType, OsintSourceType } from '../../../common/enums'
import type { BuiltinOsintSource } from '../agent-config.types'

export const BUILTIN_OSINT_SOURCES: BuiltinOsintSource[] = [
  {
    sourceType: OsintSourceType.VIRUSTOTAL,
    name: 'VirusTotal',
    baseUrl: 'https://www.virustotal.com/api/v3',
    authType: OsintAuthType.API_KEY_HEADER,
    headerName: 'x-apikey',
    responsePath: 'data.attributes',
    requestMethod: 'GET',
    supportedIocTypes: ['ip', 'domain', 'hash', 'url'],
  },
  {
    sourceType: OsintSourceType.SHODAN,
    name: 'Shodan',
    baseUrl: 'https://api.shodan.io',
    authType: OsintAuthType.API_KEY_QUERY,
    queryParamName: 'key',
    responsePath: '',
    requestMethod: 'GET',
    supportedIocTypes: ['ip'],
  },
  {
    sourceType: OsintSourceType.ABUSEIPDB,
    name: 'AbuseIPDB',
    baseUrl: 'https://api.abuseipdb.com/api/v2',
    authType: OsintAuthType.API_KEY_HEADER,
    headerName: 'Key',
    responsePath: 'data',
    requestMethod: 'GET',
    supportedIocTypes: ['ip'],
  },
  {
    sourceType: OsintSourceType.NVD_NIST,
    name: 'NVD/NIST',
    baseUrl: 'https://services.nvd.nist.gov/rest/json/cves/2.0',
    authType: OsintAuthType.NONE,
    responsePath: 'vulnerabilities',
    requestMethod: 'GET',
    supportedIocTypes: ['cve'],
  },
  {
    sourceType: OsintSourceType.ALIENVAULT_OTX,
    name: 'AlienVault OTX',
    baseUrl: 'https://otx.alienvault.com/api/v1',
    authType: OsintAuthType.API_KEY_HEADER,
    headerName: 'X-OTX-API-KEY',
    responsePath: 'results',
    requestMethod: 'GET',
    supportedIocTypes: ['ip', 'domain', 'hash', 'url'],
  },
  {
    sourceType: OsintSourceType.GREYNOISE,
    name: 'GreyNoise',
    baseUrl: 'https://api.greynoise.io/v3',
    authType: OsintAuthType.API_KEY_HEADER,
    headerName: 'key',
    responsePath: '',
    requestMethod: 'GET',
    supportedIocTypes: ['ip'],
  },
  {
    sourceType: OsintSourceType.URLSCAN,
    name: 'URLScan',
    baseUrl: 'https://urlscan.io/api/v1',
    authType: OsintAuthType.API_KEY_HEADER,
    headerName: 'API-Key',
    responsePath: '',
    requestMethod: 'GET',
    supportedIocTypes: ['url', 'domain'],
  },
  {
    sourceType: OsintSourceType.CENSYS,
    name: 'Censys',
    baseUrl: 'https://search.censys.io/api/v2',
    authType: OsintAuthType.BASIC,
    responsePath: 'result',
    requestMethod: 'GET',
    supportedIocTypes: ['ip', 'domain'],
  },
  {
    sourceType: OsintSourceType.MALWARE_BAZAAR,
    name: 'MalwareBazaar',
    baseUrl: 'https://mb-api.abuse.ch/api/v1',
    authType: OsintAuthType.NONE,
    responsePath: 'data',
    requestMethod: 'POST',
    supportedIocTypes: ['hash'],
  },
  {
    sourceType: OsintSourceType.THREATFOX,
    name: 'ThreatFox',
    baseUrl: 'https://threatfox-api.abuse.ch/api/v1',
    authType: OsintAuthType.NONE,
    responsePath: 'data',
    requestMethod: 'POST',
    supportedIocTypes: ['ip', 'domain', 'hash', 'url'],
  },
  {
    sourceType: OsintSourceType.PULSEDIVE,
    name: 'Pulsedive',
    baseUrl: 'https://pulsedive.com/api',
    authType: OsintAuthType.API_KEY_QUERY,
    queryParamName: 'key',
    responsePath: '',
    requestMethod: 'GET',
    supportedIocTypes: ['ip', 'domain', 'url'],
  },
  {
    sourceType: OsintSourceType.WEB_SEARCH,
    name: 'Web Search',
    baseUrl: 'https://api.bing.microsoft.com/v7.0/search',
    authType: OsintAuthType.API_KEY_HEADER,
    headerName: 'Ocp-Apim-Subscription-Key',
    responsePath: 'webPages.value',
    requestMethod: 'GET',
    supportedIocTypes: ['ip', 'domain', 'hash', 'cve'],
  },
]
