export enum DashboardPanelKey {
  OVERVIEW = 'overview',
  THREAT_OPERATIONS = 'threat_operations',
  AUTOMATION = 'automation',
  GOVERNANCE = 'governance',
  INFRASTRUCTURE = 'infrastructure',
  ALERT_TRENDS = 'alert_trends',
  SEVERITY_DISTRIBUTION = 'severity_distribution',
  MITRE_TECHNIQUES = 'mitre_techniques',
  TARGETED_ASSETS = 'targeted_assets',
  REPORT_TEMPLATES = 'report_templates',
  AI_CANVAS = 'ai_canvas',
  RECENT_ACTIVITY = 'recent_activity',
  CONNECTOR_SYNC = 'connector_sync',
  RULE_PERFORMANCE = 'rule_performance',
  RUNTIME_BACKLOG = 'runtime_backlog',
  AUTOMATION_QUALITY = 'automation_quality',
  EXPOSURE_SUMMARY = 'exposure_summary',
  INCIDENT_STATUS = 'incident_status',
  OPERATIONS = 'operations',
  CASE_AGING = 'case_aging',
}
