-- AlterEnum: Add new values to UserRole
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PLATFORM_OPERATOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'DETECTION_ENGINEER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'INCIDENT_RESPONDER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'THREAT_INTEL_ANALYST';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SOAR_ENGINEER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'AUDITOR_READONLY';
