export enum AgentActionType {
  CREATE = 'create',
  UPDATE = 'update',
  ENRICH = 'enrich',
  SCORE = 'score',
  CLASSIFY = 'classify',
  SUMMARIZE = 'summarize',
  DRAFT = 'draft',
  PROPOSE = 'propose',
  ESCALATE = 'escalate',
  TRIAGE = 'triage',
  CORRELATE = 'correlate',
  INVESTIGATE = 'investigate',
  RECOMMEND = 'recommend',
  VALIDATE = 'validate',
  SYNC = 'sync',
  REVIEW = 'review',
  REPORT = 'report',
  EXPLAIN = 'explain',
}
