import { AiAgentId, AiFeatureKey, AiOutputFormat, AiTriggerMode, OsintAuthType } from '@/enums'

export const AI_AGENT_LABEL_KEYS: Record<AiAgentId, string> = {
  [AiAgentId.ORCHESTRATOR]: 'aiConfig.agentOrchestrator',
  [AiAgentId.L1_ANALYST]: 'aiConfig.agentL1Analyst',
  [AiAgentId.L2_ANALYST]: 'aiConfig.agentL2Analyst',
  [AiAgentId.THREAT_HUNTER]: 'aiConfig.agentThreatHunter',
  [AiAgentId.RULES_ANALYST]: 'aiConfig.agentRulesAnalyst',
  [AiAgentId.NORM_VERIFIER]: 'aiConfig.agentNormVerifier',
  [AiAgentId.DASHBOARD_BUILDER]: 'aiConfig.agentDashboardBuilder',
  [AiAgentId.ALERT_TRIAGE]: 'aiConfig.agentAlertTriage',
  [AiAgentId.CASE_CREATION]: 'aiConfig.agentCaseCreation',
  [AiAgentId.INCIDENT_ESCALATION]: 'aiConfig.agentIncidentEscalation',
  [AiAgentId.CORRELATION_SYNTHESIS]: 'aiConfig.agentCorrelationSynthesis',
  [AiAgentId.SIGMA_DRAFTING]: 'aiConfig.agentSigmaDrafting',
  [AiAgentId.VULN_PRIORITIZATION]: 'aiConfig.agentVulnPrioritization',
  [AiAgentId.UEBA_NARRATIVE]: 'aiConfig.agentUebaNarrative',
  [AiAgentId.ATTACK_PATH_SUMMARY]: 'aiConfig.agentAttackPathSummary',
  [AiAgentId.NORM_VERIFICATION]: 'aiConfig.agentNormVerification',
  [AiAgentId.RULES_HYGIENE]: 'aiConfig.agentRulesHygiene',
  [AiAgentId.REPORTING]: 'aiConfig.agentReporting',
  [AiAgentId.ENTITY_LINKING]: 'aiConfig.agentEntityLinking',
  [AiAgentId.JOB_HEALTH]: 'aiConfig.agentJobHealth',
  [AiAgentId.CLOUD_TRIAGE]: 'aiConfig.agentCloudTriage',
  [AiAgentId.SOAR_DRAFTING]: 'aiConfig.agentSoarDrafting',
  [AiAgentId.THREAT_INTEL_SYNTHESIS]: 'aiConfig.agentThreatIntelSynthesis',
  [AiAgentId.IOC_ENRICHMENT]: 'aiConfig.agentIocEnrichment',
  [AiAgentId.MISP_FEED_REVIEW]: 'aiConfig.agentMispFeedReview',
  [AiAgentId.KNOWLEDGE_BASE]: 'aiConfig.agentKnowledgeBase',
  [AiAgentId.NOTIFICATION_DIGEST]: 'aiConfig.agentNotificationDigest',
  [AiAgentId.PROVIDER_HEALTH]: 'aiConfig.agentProviderHealth',
  [AiAgentId.APPROVAL_ADVISOR]: 'aiConfig.agentApprovalAdvisor',
}

export const AI_AGENT_DESCRIPTION_KEYS: Record<AiAgentId, string> = {
  [AiAgentId.ORCHESTRATOR]: 'aiConfig.agentOrchestratorDesc',
  [AiAgentId.L1_ANALYST]: 'aiConfig.agentL1AnalystDesc',
  [AiAgentId.L2_ANALYST]: 'aiConfig.agentL2AnalystDesc',
  [AiAgentId.THREAT_HUNTER]: 'aiConfig.agentThreatHunterDesc',
  [AiAgentId.RULES_ANALYST]: 'aiConfig.agentRulesAnalystDesc',
  [AiAgentId.NORM_VERIFIER]: 'aiConfig.agentNormVerifierDesc',
  [AiAgentId.DASHBOARD_BUILDER]: 'aiConfig.agentDashboardBuilderDesc',
  [AiAgentId.ALERT_TRIAGE]: 'aiConfig.agentAlertTriageDesc',
  [AiAgentId.CASE_CREATION]: 'aiConfig.agentCaseCreationDesc',
  [AiAgentId.INCIDENT_ESCALATION]: 'aiConfig.agentIncidentEscalationDesc',
  [AiAgentId.CORRELATION_SYNTHESIS]: 'aiConfig.agentCorrelationSynthesisDesc',
  [AiAgentId.SIGMA_DRAFTING]: 'aiConfig.agentSigmaDraftingDesc',
  [AiAgentId.VULN_PRIORITIZATION]: 'aiConfig.agentVulnPrioritizationDesc',
  [AiAgentId.UEBA_NARRATIVE]: 'aiConfig.agentUebaNarrativeDesc',
  [AiAgentId.ATTACK_PATH_SUMMARY]: 'aiConfig.agentAttackPathSummaryDesc',
  [AiAgentId.NORM_VERIFICATION]: 'aiConfig.agentNormVerificationDesc',
  [AiAgentId.RULES_HYGIENE]: 'aiConfig.agentRulesHygieneDesc',
  [AiAgentId.REPORTING]: 'aiConfig.agentReportingDesc',
  [AiAgentId.ENTITY_LINKING]: 'aiConfig.agentEntityLinkingDesc',
  [AiAgentId.JOB_HEALTH]: 'aiConfig.agentJobHealthDesc',
  [AiAgentId.CLOUD_TRIAGE]: 'aiConfig.agentCloudTriageDesc',
  [AiAgentId.SOAR_DRAFTING]: 'aiConfig.agentSoarDraftingDesc',
  [AiAgentId.THREAT_INTEL_SYNTHESIS]: 'aiConfig.agentThreatIntelSynthesisDesc',
  [AiAgentId.IOC_ENRICHMENT]: 'aiConfig.agentIocEnrichmentDesc',
  [AiAgentId.MISP_FEED_REVIEW]: 'aiConfig.agentMispFeedReviewDesc',
  [AiAgentId.KNOWLEDGE_BASE]: 'aiConfig.agentKnowledgeBaseDesc',
  [AiAgentId.NOTIFICATION_DIGEST]: 'aiConfig.agentNotificationDigestDesc',
  [AiAgentId.PROVIDER_HEALTH]: 'aiConfig.agentProviderHealthDesc',
  [AiAgentId.APPROVAL_ADVISOR]: 'aiConfig.agentApprovalAdvisorDesc',
}

export const AI_TRIGGER_MODE_LABEL_KEYS: Record<AiTriggerMode, string> = {
  [AiTriggerMode.MANUAL_ONLY]: 'aiConfig.triggerManual',
  [AiTriggerMode.AUTO_ON_ALERT]: 'aiConfig.triggerAutoAlert',
  [AiTriggerMode.AUTO_BY_AGENT]: 'aiConfig.triggerAutoAgent',
  [AiTriggerMode.SCHEDULED]: 'aiConfig.triggerScheduled',
}

export const AI_OUTPUT_FORMAT_LABEL_KEYS: Record<AiOutputFormat, string> = {
  [AiOutputFormat.STRUCTURED_JSON]: 'aiConfig.outputJson',
  [AiOutputFormat.MARKDOWN]: 'aiConfig.outputMarkdown',
  [AiOutputFormat.RICH_CARDS]: 'aiConfig.outputRichCards',
  [AiOutputFormat.PLAIN_TEXT]: 'aiConfig.outputPlainText',
}

export const OSINT_AUTH_TYPE_LABELS: Record<OsintAuthType, string> = {
  [OsintAuthType.NONE]: 'None',
  [OsintAuthType.API_KEY_HEADER]: 'API Key (Header)',
  [OsintAuthType.API_KEY_QUERY]: 'API Key (Query Param)',
  [OsintAuthType.BEARER]: 'Bearer Token',
  [OsintAuthType.BASIC]: 'Basic Auth (user:pass)',
}

/**
 * Maps specialist agent IDs to their core execution agent.
 * Used in UI to show which core agent handles the specialist's work.
 */
export const AGENT_EXECUTION_MAP: Partial<Record<AiAgentId, AiAgentId>> = {
  [AiAgentId.ALERT_TRIAGE]: AiAgentId.L1_ANALYST,
  [AiAgentId.CASE_CREATION]: AiAgentId.L2_ANALYST,
  [AiAgentId.INCIDENT_ESCALATION]: AiAgentId.L2_ANALYST,
  [AiAgentId.CORRELATION_SYNTHESIS]: AiAgentId.L2_ANALYST,
  [AiAgentId.SIGMA_DRAFTING]: AiAgentId.RULES_ANALYST,
  [AiAgentId.VULN_PRIORITIZATION]: AiAgentId.L2_ANALYST,
  [AiAgentId.UEBA_NARRATIVE]: AiAgentId.L2_ANALYST,
  [AiAgentId.ATTACK_PATH_SUMMARY]: AiAgentId.THREAT_HUNTER,
  [AiAgentId.NORM_VERIFICATION]: AiAgentId.NORM_VERIFIER,
  [AiAgentId.RULES_HYGIENE]: AiAgentId.RULES_ANALYST,
  [AiAgentId.REPORTING]: AiAgentId.DASHBOARD_BUILDER,
  [AiAgentId.ENTITY_LINKING]: AiAgentId.L2_ANALYST,
  [AiAgentId.JOB_HEALTH]: AiAgentId.ORCHESTRATOR,
  [AiAgentId.CLOUD_TRIAGE]: AiAgentId.L1_ANALYST,
  [AiAgentId.SOAR_DRAFTING]: AiAgentId.ORCHESTRATOR,
  [AiAgentId.THREAT_INTEL_SYNTHESIS]: AiAgentId.L2_ANALYST,
  [AiAgentId.IOC_ENRICHMENT]: AiAgentId.L2_ANALYST,
  [AiAgentId.MISP_FEED_REVIEW]: AiAgentId.L2_ANALYST,
  [AiAgentId.KNOWLEDGE_BASE]: AiAgentId.L1_ANALYST,
  [AiAgentId.NOTIFICATION_DIGEST]: AiAgentId.ORCHESTRATOR,
  [AiAgentId.PROVIDER_HEALTH]: AiAgentId.ORCHESTRATOR,
  [AiAgentId.APPROVAL_ADVISOR]: AiAgentId.ORCHESTRATOR,
}

export const AI_FEATURE_KEY_LABEL_KEYS: Record<AiFeatureKey, string> = {
  [AiFeatureKey.ALERT_SUMMARIZE]: 'featureAlertSummarize',
  [AiFeatureKey.ALERT_EXPLAIN_SEVERITY]: 'featureAlertExplainSeverity',
  [AiFeatureKey.ALERT_FALSE_POSITIVE_SCORE]: 'featureAlertFalsePositive',
  [AiFeatureKey.ALERT_NEXT_ACTION]: 'featureAlertNextAction',
  [AiFeatureKey.CASE_SUMMARIZE]: 'featureCaseSummarize',
  [AiFeatureKey.CASE_EXECUTIVE_SUMMARY]: 'featureCaseExecutiveSummary',
  [AiFeatureKey.CASE_TIMELINE]: 'featureCaseTimeline',
  [AiFeatureKey.CASE_NEXT_TASKS]: 'featureCaseNextTasks',
  [AiFeatureKey.HUNT_HYPOTHESIS]: 'featureHuntHypothesis',
  [AiFeatureKey.HUNT_NL_TO_QUERY]: 'featureHuntNlToQuery',
  [AiFeatureKey.HUNT_RESULT_INTERPRET]: 'featureHuntResultInterpret',
  [AiFeatureKey.INTEL_IOC_ENRICH]: 'featureIntelIocEnrich',
  [AiFeatureKey.INTEL_ADVISORY_DRAFT]: 'featureIntelAdvisoryDraft',
  [AiFeatureKey.DETECTION_RULE_DRAFT]: 'featureDetectionRuleDraft',
  [AiFeatureKey.DETECTION_TUNING]: 'featureDetectionTuning',
  [AiFeatureKey.REPORT_DAILY_SUMMARY]: 'featureReportDailySummary',
  [AiFeatureKey.REPORT_EXECUTIVE]: 'featureReportExecutive',
  [AiFeatureKey.DASHBOARD_ANOMALY]: 'featureDashboardAnomaly',
  [AiFeatureKey.SOAR_PLAYBOOK_DRAFT]: 'featureSoarPlaybookDraft',
  [AiFeatureKey.AGENT_TASK]: 'featureAgentTask',
  [AiFeatureKey.KNOWLEDGE_SEARCH]: 'featureKnowledgeSearch',
  [AiFeatureKey.KNOWLEDGE_GENERATE_RUNBOOK]: 'featureKnowledgeGenerateRunbook',
  [AiFeatureKey.KNOWLEDGE_SUMMARIZE_INCIDENT]: 'featureKnowledgeSummarizeIncident',
  [AiFeatureKey.ENTITY_RISK_EXPLAIN]: 'featureEntityRiskExplain',
  [AiFeatureKey.NORMALIZATION_VERIFY]: 'featureNormalizationVerify',
}
