import { OsintAuthType, OsintSourceType } from '@/enums'
import type { BuiltinOsintSourceDefaults } from '@/types'

export const BUILTIN_OSINT_DEFAULTS: Record<
  Exclude<OsintSourceType, OsintSourceType.CUSTOM>,
  BuiltinOsintSourceDefaults
> = {
  [OsintSourceType.VIRUSTOTAL]: {
    baseUrl: 'https://www.virustotal.com/api/v3',
    authType: OsintAuthType.API_KEY_HEADER,
    headerName: 'x-apikey',
    queryParamName: '',
    responsePath: 'data.attributes',
    requestMethod: 'GET',
    supportedIocTypes: ['ip', 'domain', 'hash', 'url'],
    rateLimitHint: '4 req/min (free), 500 req/min (premium)',
  },
  [OsintSourceType.SHODAN]: {
    baseUrl: 'https://api.shodan.io',
    authType: OsintAuthType.API_KEY_QUERY,
    headerName: '',
    queryParamName: 'key',
    responsePath: '',
    requestMethod: 'GET',
    supportedIocTypes: ['ip'],
    rateLimitHint: '1 req/sec (free)',
  },
  [OsintSourceType.ABUSEIPDB]: {
    baseUrl: 'https://api.abuseipdb.com/api/v2',
    authType: OsintAuthType.API_KEY_HEADER,
    headerName: 'Key',
    queryParamName: '',
    responsePath: 'data',
    requestMethod: 'GET',
    supportedIocTypes: ['ip'],
    rateLimitHint: '1000 req/day (free)',
  },
  [OsintSourceType.NVD_NIST]: {
    baseUrl: 'https://services.nvd.nist.gov/rest/json/cves/2.0',
    authType: OsintAuthType.NONE,
    headerName: '',
    queryParamName: '',
    responsePath: 'vulnerabilities',
    requestMethod: 'GET',
    supportedIocTypes: ['cve'],
    rateLimitHint: '5 req/30sec (no key), 50 req/30sec (with key)',
  },
  [OsintSourceType.ALIENVAULT_OTX]: {
    baseUrl: 'https://otx.alienvault.com/api/v1',
    authType: OsintAuthType.API_KEY_HEADER,
    headerName: 'X-OTX-API-KEY',
    queryParamName: '',
    responsePath: 'results',
    requestMethod: 'GET',
    supportedIocTypes: ['ip', 'domain', 'hash', 'url'],
    rateLimitHint: '10000 req/hour',
  },
  [OsintSourceType.GREYNOISE]: {
    baseUrl: 'https://api.greynoise.io/v3',
    authType: OsintAuthType.API_KEY_HEADER,
    headerName: 'key',
    queryParamName: '',
    responsePath: '',
    requestMethod: 'GET',
    supportedIocTypes: ['ip'],
    rateLimitHint: '500 req/day (community)',
  },
  [OsintSourceType.URLSCAN]: {
    baseUrl: 'https://urlscan.io/api/v1',
    authType: OsintAuthType.API_KEY_HEADER,
    headerName: 'API-Key',
    queryParamName: '',
    responsePath: '',
    requestMethod: 'GET',
    supportedIocTypes: ['url', 'domain'],
    rateLimitHint: '100 req/min (private), 2 req/min (public)',
  },
  [OsintSourceType.CENSYS]: {
    baseUrl: 'https://search.censys.io/api/v2',
    authType: OsintAuthType.BASIC,
    headerName: '',
    queryParamName: '',
    responsePath: 'result',
    requestMethod: 'GET',
    supportedIocTypes: ['ip', 'domain'],
    rateLimitHint: '0.4 req/sec (free)',
  },
  [OsintSourceType.MALWARE_BAZAAR]: {
    baseUrl: 'https://mb-api.abuse.ch/api/v1',
    authType: OsintAuthType.NONE,
    headerName: '',
    queryParamName: '',
    responsePath: 'data',
    requestMethod: 'POST',
    supportedIocTypes: ['hash'],
    rateLimitHint: 'No documented limit',
  },
  [OsintSourceType.THREATFOX]: {
    baseUrl: 'https://threatfox-api.abuse.ch/api/v1',
    authType: OsintAuthType.NONE,
    headerName: '',
    queryParamName: '',
    responsePath: 'data',
    requestMethod: 'POST',
    supportedIocTypes: ['ip', 'domain', 'hash', 'url'],
    rateLimitHint: 'No documented limit',
  },
  [OsintSourceType.PULSEDIVE]: {
    baseUrl: 'https://pulsedive.com/api',
    authType: OsintAuthType.API_KEY_QUERY,
    headerName: '',
    queryParamName: 'key',
    responsePath: '',
    requestMethod: 'GET',
    supportedIocTypes: ['ip', 'domain', 'url'],
    rateLimitHint: '30 req/min (free)',
  },
  [OsintSourceType.WEB_SEARCH]: {
    baseUrl: 'https://api.bing.microsoft.com/v7.0/search',
    authType: OsintAuthType.API_KEY_HEADER,
    headerName: 'Ocp-Apim-Subscription-Key',
    queryParamName: '',
    responsePath: 'webPages.value',
    requestMethod: 'GET',
    supportedIocTypes: ['ip', 'domain', 'hash', 'cve'],
    rateLimitHint: '3 req/sec (free)',
  },
}
