import { AiAgentId, AiFeatureKey, AiOutputFormat, AiTriggerMode } from '../../common/enums'
import type { AgentDefaultConfig } from './agent-config.types'

/** The connector key that means "use tenant default / auto-select" */
export const AI_DEFAULT_PROVIDER_KEY = 'default'

export const AI_AGENT_DEFAULTS: Record<AiAgentId, AgentDefaultConfig> = {
  [AiAgentId.ORCHESTRATOR]: {
    displayName: 'Orchestrator',
    description: 'Coordinates multi-agent workflows and routes tasks to specialist agents',
    temperature: 0.3,
    maxTokensPerCall: 4096,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.STRUCTURED_JSON,
    presentationSkills: ['task_routing', 'workflow_summary'],
  },
  [AiAgentId.L1_ANALYST]: {
    displayName: 'L1 SOC Analyst',
    description: 'Performs initial alert triage, enrichment, and classification',
    temperature: 0.5,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.AUTO_ON_ALERT,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['risk_gauge', 'ioc_table', 'severity_badge'],
  },
  [AiAgentId.L2_ANALYST]: {
    displayName: 'L2 SOC Analyst',
    description: 'Deep investigation, correlation analysis, and incident assessment',
    temperature: 0.5,
    maxTokensPerCall: 4096,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['timeline', 'mitre_map', 'ioc_table', 'risk_gauge'],
  },
  [AiAgentId.THREAT_HUNTER]: {
    displayName: 'Threat Hunter',
    description: 'Proactive threat hunting, hypothesis generation, and hunt query creation',
    temperature: 0.7,
    maxTokensPerCall: 4096,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.MARKDOWN,
    presentationSkills: ['hunt_query', 'mitre_map', 'ioc_table'],
  },
  [AiAgentId.RULES_ANALYST]: {
    displayName: 'Rules Analyst',
    description: 'Detection rule creation, tuning, and Sigma/YARA analysis',
    temperature: 0.4,
    maxTokensPerCall: 4096,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.STRUCTURED_JSON,
    presentationSkills: ['rule_preview', 'mitre_map'],
  },
  [AiAgentId.NORM_VERIFIER]: {
    displayName: 'Normalization Verifier',
    description: 'Log normalization pipeline verification and field mapping validation',
    temperature: 0.3,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.STRUCTURED_JSON,
    presentationSkills: ['field_mapping_table', 'validation_report'],
  },
  [AiAgentId.DASHBOARD_BUILDER]: {
    displayName: 'Dashboard Builder',
    description:
      'KPI suggestions, visualization recommendations, and dashboard layout optimization',
    temperature: 0.6,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['chart_preview', 'kpi_card'],
  },
  [AiAgentId.ALERT_TRIAGE]: {
    displayName: 'Alert Triage Agent',
    description: 'Auto-triage and score alerts',
    temperature: 0.4,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.AUTO_ON_ALERT,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['risk_gauge', 'severity_badge'],
  },
  [AiAgentId.CASE_CREATION]: {
    displayName: 'Case Creation Agent',
    description: 'Create case drafts from grouped alerts',
    temperature: 0.5,
    maxTokensPerCall: 4096,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.STRUCTURED_JSON,
    presentationSkills: ['case_preview'],
  },
  [AiAgentId.INCIDENT_ESCALATION]: {
    displayName: 'Incident Escalation Agent',
    description: 'Escalate critical incidents',
    temperature: 0.3,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['severity_badge', 'timeline'],
  },
  [AiAgentId.CORRELATION_SYNTHESIS]: {
    displayName: 'Correlation Synthesis Agent',
    description: 'Discover cross-source correlations',
    temperature: 0.5,
    maxTokensPerCall: 4096,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['timeline', 'ioc_table', 'mitre_map'],
  },
  [AiAgentId.SIGMA_DRAFTING]: {
    displayName: 'Sigma Drafting Agent',
    description: 'Draft Sigma detection rules',
    temperature: 0.4,
    maxTokensPerCall: 4096,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.STRUCTURED_JSON,
    presentationSkills: ['rule_preview'],
  },
  [AiAgentId.VULN_PRIORITIZATION]: {
    displayName: 'Vulnerability Prioritization Agent',
    description: 'Prioritize vulnerabilities by risk',
    temperature: 0.4,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['risk_gauge', 'severity_badge'],
  },
  [AiAgentId.UEBA_NARRATIVE]: {
    displayName: 'UEBA Narrative Agent',
    description: 'Explain behavioral anomalies',
    temperature: 0.6,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.MARKDOWN,
    presentationSkills: ['timeline', 'risk_gauge'],
  },
  [AiAgentId.ATTACK_PATH_SUMMARY]: {
    displayName: 'Attack Path Summarization Agent',
    description: 'Summarize attack chains',
    temperature: 0.5,
    maxTokensPerCall: 4096,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['timeline', 'mitre_map'],
  },
  [AiAgentId.NORM_VERIFICATION]: {
    displayName: 'Normalization Verification Agent',
    description: 'Verify parser quality',
    temperature: 0.3,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.STRUCTURED_JSON,
    presentationSkills: ['field_mapping_table', 'validation_report'],
  },
  [AiAgentId.RULES_HYGIENE]: {
    displayName: 'Rules Hygiene Agent',
    description: 'Detect stale/conflicting rules',
    temperature: 0.4,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['rule_preview'],
  },
  [AiAgentId.REPORTING]: {
    displayName: 'Reporting Agent',
    description: 'Generate SOC reports',
    temperature: 0.5,
    maxTokensPerCall: 4096,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.MARKDOWN,
    presentationSkills: ['chart_preview', 'kpi_card'],
  },
  [AiAgentId.ENTITY_LINKING]: {
    displayName: 'Entity Graph Linking Agent',
    description: 'Discover entity relationships',
    temperature: 0.5,
    maxTokensPerCall: 4096,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['ioc_table'],
  },
  [AiAgentId.JOB_HEALTH]: {
    displayName: 'Job Health Agent',
    description: 'Monitor job queue health',
    temperature: 0.3,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.SCHEDULED,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['kpi_card'],
  },
  [AiAgentId.CLOUD_TRIAGE]: {
    displayName: 'Cloud Triage Agent',
    description: 'Triage cloud security findings',
    temperature: 0.4,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['risk_gauge', 'severity_badge'],
  },
  [AiAgentId.SOAR_DRAFTING]: {
    displayName: 'SOAR Drafting Agent',
    description: 'Draft SOAR playbooks',
    temperature: 0.5,
    maxTokensPerCall: 4096,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.STRUCTURED_JSON,
    presentationSkills: ['workflow_summary'],
  },
  [AiAgentId.THREAT_INTEL_SYNTHESIS]: {
    displayName: 'Threat Intel Synthesis Agent',
    description: 'Synthesize threat intelligence',
    temperature: 0.5,
    maxTokensPerCall: 4096,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['ioc_table', 'mitre_map'],
  },
  [AiAgentId.IOC_ENRICHMENT]: {
    displayName: 'IOC Enrichment Agent',
    description: 'Enrich IOCs from OSINT sources',
    temperature: 0.4,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['ioc_table', 'risk_gauge'],
  },
  [AiAgentId.MISP_FEED_REVIEW]: {
    displayName: 'MISP Feed Review Agent',
    description: 'Review MISP event feeds',
    temperature: 0.4,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['ioc_table'],
  },
  [AiAgentId.KNOWLEDGE_BASE]: {
    displayName: 'Knowledge Base Agent',
    description: 'Extract reusable knowledge',
    temperature: 0.5,
    maxTokensPerCall: 4096,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.MARKDOWN,
    presentationSkills: ['workflow_summary'],
  },
  [AiAgentId.NOTIFICATION_DIGEST]: {
    displayName: 'Notification Digest Agent',
    description: 'Generate notification digests',
    temperature: 0.4,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.SCHEDULED,
    outputFormat: AiOutputFormat.MARKDOWN,
    presentationSkills: ['kpi_card'],
  },
  [AiAgentId.PROVIDER_HEALTH]: {
    displayName: 'Provider Health Agent',
    description: 'Monitor AI provider health',
    temperature: 0.3,
    maxTokensPerCall: 1024,
    triggerMode: AiTriggerMode.SCHEDULED,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['kpi_card'],
  },
  [AiAgentId.APPROVAL_ADVISOR]: {
    displayName: 'Approval Advisor Agent',
    description: 'Advise on pending approvals',
    temperature: 0.4,
    maxTokensPerCall: 2048,
    triggerMode: AiTriggerMode.MANUAL_ONLY,
    outputFormat: AiOutputFormat.RICH_CARDS,
    presentationSkills: ['risk_gauge', 'severity_badge'],
  },
}

export const AGENT_DEFAULTS_MAP = new Map<string, AgentDefaultConfig>(
  Object.entries(AI_AGENT_DEFAULTS)
)

/**
 * Maps each AI feature to the agent responsible for handling it.
 * Used by AiService.executeAiTask() to load per-agent configuration
 * (temperature, maxTokens, systemPrompt, quota, etc.) at execution time.
 */
export const FEATURE_TO_AGENT_MAP: Record<AiFeatureKey, AiAgentId> = {
  [AiFeatureKey.ALERT_SUMMARIZE]: AiAgentId.L1_ANALYST,
  [AiFeatureKey.ALERT_EXPLAIN_SEVERITY]: AiAgentId.L1_ANALYST,
  [AiFeatureKey.ALERT_FALSE_POSITIVE_SCORE]: AiAgentId.L1_ANALYST,
  [AiFeatureKey.ALERT_NEXT_ACTION]: AiAgentId.L1_ANALYST,
  [AiFeatureKey.CASE_SUMMARIZE]: AiAgentId.L2_ANALYST,
  [AiFeatureKey.CASE_EXECUTIVE_SUMMARY]: AiAgentId.L2_ANALYST,
  [AiFeatureKey.CASE_TIMELINE]: AiAgentId.L2_ANALYST,
  [AiFeatureKey.CASE_NEXT_TASKS]: AiAgentId.L2_ANALYST,
  [AiFeatureKey.HUNT_HYPOTHESIS]: AiAgentId.THREAT_HUNTER,
  [AiFeatureKey.HUNT_NL_TO_QUERY]: AiAgentId.THREAT_HUNTER,
  [AiFeatureKey.HUNT_RESULT_INTERPRET]: AiAgentId.THREAT_HUNTER,
  [AiFeatureKey.INTEL_IOC_ENRICH]: AiAgentId.L2_ANALYST,
  [AiFeatureKey.INTEL_ADVISORY_DRAFT]: AiAgentId.L2_ANALYST,
  [AiFeatureKey.DETECTION_RULE_DRAFT]: AiAgentId.RULES_ANALYST,
  [AiFeatureKey.DETECTION_TUNING]: AiAgentId.RULES_ANALYST,
  [AiFeatureKey.REPORT_DAILY_SUMMARY]: AiAgentId.DASHBOARD_BUILDER,
  [AiFeatureKey.REPORT_EXECUTIVE]: AiAgentId.DASHBOARD_BUILDER,
  [AiFeatureKey.DASHBOARD_ANOMALY]: AiAgentId.DASHBOARD_BUILDER,
  [AiFeatureKey.SOAR_PLAYBOOK_DRAFT]: AiAgentId.ORCHESTRATOR,
  [AiFeatureKey.AGENT_TASK]: AiAgentId.ORCHESTRATOR,
  [AiFeatureKey.KNOWLEDGE_SEARCH]: AiAgentId.L1_ANALYST,
  [AiFeatureKey.KNOWLEDGE_GENERATE_RUNBOOK]: AiAgentId.L2_ANALYST,
  [AiFeatureKey.KNOWLEDGE_SUMMARIZE_INCIDENT]: AiAgentId.L2_ANALYST,
  [AiFeatureKey.ENTITY_RISK_EXPLAIN]: AiAgentId.L2_ANALYST,
  [AiFeatureKey.NORMALIZATION_VERIFY]: AiAgentId.NORM_VERIFIER,
  [AiFeatureKey.VULNERABILITY_PRIORITIZE]: AiAgentId.L2_ANALYST,
  [AiFeatureKey.CLOUD_FINDING_TRIAGE]: AiAgentId.L1_ANALYST,
  [AiFeatureKey.UEBA_ANOMALY_EXPLAIN]: AiAgentId.L2_ANALYST,
  [AiFeatureKey.ATTACK_PATH_SUMMARIZE]: AiAgentId.THREAT_HUNTER,
}

/**
 * Maps orphaned specialist agent IDs to their real execution agent.
 * These specialist IDs appear in UI agent cards and schedule configs
 * but have no direct execution handler — they delegate to the core agents.
 * This allows toggling specialist agents to control feature subsets.
 */
export const AGENT_ALIAS_MAP: Record<string, AiAgentId> = {
  [AiAgentId.ALERT_TRIAGE]: AiAgentId.L1_ANALYST,
  [AiAgentId.CASE_CREATION]: AiAgentId.L2_ANALYST,
  [AiAgentId.INCIDENT_ESCALATION]: AiAgentId.L2_ANALYST,
  [AiAgentId.CORRELATION_SYNTHESIS]: AiAgentId.L2_ANALYST,
  [AiAgentId.SIGMA_DRAFTING]: AiAgentId.RULES_ANALYST,
  [AiAgentId.VULN_PRIORITIZATION]: AiAgentId.L2_ANALYST,
  [AiAgentId.UEBA_NARRATIVE]: AiAgentId.L2_ANALYST,
  [AiAgentId.ATTACK_PATH_SUMMARY]: AiAgentId.THREAT_HUNTER,
  [AiAgentId.NORM_VERIFICATION]: AiAgentId.NORM_VERIFIER,
  [AiAgentId.RULES_HYGIENE]: AiAgentId.RULES_ANALYST,
  [AiAgentId.REPORTING]: AiAgentId.DASHBOARD_BUILDER,
  [AiAgentId.ENTITY_LINKING]: AiAgentId.L2_ANALYST,
  [AiAgentId.JOB_HEALTH]: AiAgentId.ORCHESTRATOR,
  [AiAgentId.CLOUD_TRIAGE]: AiAgentId.L1_ANALYST,
  [AiAgentId.SOAR_DRAFTING]: AiAgentId.ORCHESTRATOR,
  [AiAgentId.THREAT_INTEL_SYNTHESIS]: AiAgentId.L2_ANALYST,
  [AiAgentId.IOC_ENRICHMENT]: AiAgentId.L2_ANALYST,
  [AiAgentId.MISP_FEED_REVIEW]: AiAgentId.L2_ANALYST,
  [AiAgentId.KNOWLEDGE_BASE]: AiAgentId.L1_ANALYST,
  [AiAgentId.NOTIFICATION_DIGEST]: AiAgentId.ORCHESTRATOR,
  [AiAgentId.PROVIDER_HEALTH]: AiAgentId.ORCHESTRATOR,
  [AiAgentId.APPROVAL_ADVISOR]: AiAgentId.ORCHESTRATOR,
}

/**
 * Resolves an agent ID to its execution agent.
 * If the agent has an alias, returns the real execution agent.
 * If not, returns the original ID (it's already a core agent).
 */
export function resolveExecutionAgent(agentId: string): string {
  return (AGENT_ALIAS_MAP[agentId] as string | undefined) ?? agentId
}
